"""Added cyclist

Revision ID: 307a058ea70f
Revises: 3423da6ccf19
Create Date: 2022-11-07 11:03:17.706825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307a058ea70f'
down_revision = '3423da6ccf19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cyclist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cyclist')
    # ### end Alembic commands ###
