"""Add type to bikes

Revision ID: 3423da6ccf19
Revises: 4d86cd972348
Create Date: 2022-10-27 14:56:26.345368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3423da6ccf19'
down_revision = '4d86cd972348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike', 'type')
    # ### end Alembic commands ###
