"""Updated relationship between cyclist and bike

Revision ID: 974dfcc3c598
Revises: 307a058ea70f
Create Date: 2022-11-07 11:13:18.104822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974dfcc3c598'
down_revision = '307a058ea70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('cyclist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bike', 'cyclist', ['cyclist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bike', type_='foreignkey')
    op.drop_column('bike', 'cyclist_id')
    # ### end Alembic commands ###
